name: "map-ci export"
on: push

jobs:
  export-map:
    name: Map Export
    runs-on: ubuntu-latest
#    container:
#      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/templates
#          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Map Build
        run: |
          mkdir -v -p build/map
          cp sandbox/* build/map
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mapping
          path: build/map
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
#      - name: Install rsync 📚
#        run: |
#          sudo apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/map # The folder the action should deploy
